phraseapp:
  project_id: "0de528b206c7050e8eb4940147448184"
  file_format: "json"
  pull:
    targets:
    - file: "./src/lang/<locale_code>.json"
      params:
        file_format: "nested_json"
  push:
    sources:
    - file: "./src/lang/<locale_code>.json"
      params:
        file_format: "nested_json"