phraseapp:
  project_id: "cdd3a87fd7a3dab18427849dcc8bd2aa"
  file_format: "json"
  pull:
    targets:
    - file: "./src/lang/<locale_code>.js"
      params:
        file_format: "nested_json"
  push:
    sources:
    - file: "./src/lang/<locale_code>.js"
      params:
        file_format: "nested_json"